package excepcionesEjerciciones;


public class ManejoExcepciones {

	
	
	public static void main (String[]args)throws Exception ,ArithmeticException{
		//primera opción
		int a=0;
		int b=300;
		int c;
		System.out.println("PRIMER BLOQUE DE EXCEPCIONES: ");
		try {
			c=a/b;
			System.out.println("El resultado es: "+c);
		}finally{
			System.out.println("Programa finalizado");
			
		}
		
		//segunda opción
		System.out.println("SEGUNDO BLOQUE DE EXCEPCIONES: ");
		int d=0;
		int g=300;
		int f;
		try {
			f=d/g;
			System.out.println("El resultado es: "+f);
			
		
		}catch(ArithmeticException e){
			System.out.println("Ha habido un error");
			e.printStackTrace();
			throw(new Exception());
		}finally{
			System.out.println("Programa finalizado");
			
		}
		
		
		
	}


}
